name: Run JUnit API Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Latest version

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'zulu'
          architecture: 'x64'

      - name: Install Google Chrome & ChromeDriver
        run: |
          choco install googlechrome -y --ignore-checksums
          choco install chromedriver -y --ignore-checksums
        shell: pwsh

      - name: Build with Maven
        run: mvn clean install

      - name: Run Tests
        run: mvn test

      - name: Install Allure CLI
        run: |
          curl -o allure.zip -Ls "https://github.com/allure-framework/allure2/releases/latest/download/allure-commandline.zip"
          powershell -Command "Expand-Archive -Path allure.zip -DestinationPath allure"
          echo "${{ github.workspace }}/allure/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Generate Allure Report
        run: mvn allure:report

      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/site/allure-maven-plugin  # The Allure report directory
          retention-days: 7  # The report will be stored for 7 days

      - name: Print Download Instructions
        run: echo "You can download the Allure report from the GitHub Actions artifacts."
