name: Run JUnit API Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'zulu'
          architecture: 'x64'

      - name: Install Google Chrome & ChromeDriver
        run: |
          choco install googlechrome -y --ignore-checksums
          choco install chromedriver -y --ignore-checksums
        shell: pwsh

      - name: Build with Maven
        run: mvn clean install

      - name: Run Tests
        run: mvn test

      - name: Install Allure CLI
        run: |
          $allure_version = "2.22.5"
          $allure_url = "https://github.com/allure-framework/allure2/releases/download/$allure_version/allure-$allure_version.zip"
          Invoke-WebRequest -Uri $allure_url -OutFile "allure.zip"
          Expand-Archive -Path "allure.zip" -DestinationPath "allure" -Force
          $allure_bin = Get-ChildItem -Path "allure" -Directory | Select-Object -ExpandProperty FullName | Select-Object -First 1
          echo "$allure_bin/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        shell: pwsh

      - name: Verify Allure Installation
        run: |
          $allure_bin = Get-ChildItem -Path "allure" -Directory | Select-Object -ExpandProperty FullName | Select-Object -First 1
          if (-Not (Test-Path "$allure_bin/bin/allure.bat")) {
            Write-Host "❌ ERROR: Allure executable not found at $allure_bin/bin/allure.bat"
            exit 1
          }
          Write-Host "✅ Allure installed successfully at: $allure_bin"
        shell: pwsh

      - name: Generate Allure Report
        run: |
          $allure_bin = Get-ChildItem -Path "allure" -Directory | Select-Object -ExpandProperty FullName | Select-Object -First 1
          & "$allure_bin/bin/allure.bat" generate target/allure-results -o target/allure-report --clean
        shell: pwsh

      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/allure-report
          retention-days: 7

      - name: Print Download Instructions
        run: echo "✅ You can download the Allure report from the GitHub Actions artifacts."
